### ISSUE TITLE
start of the game 

### ISSUE THREAD

**Issue by gaveer** [LiangYuxuan/FreeInstanceSharer#1]
1x FreeInstanceSharer\Locales\zhCN-Simplified Chinese.lua:4: attempt to index local 'L' (a nil value)
FreeInstanceSharer\Locales\zhCN-Simplified Chinese.lua:4: in main chunk

Locals:
addonName = "FreeInstanceSharer"
addon = <table> {
}
L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @Ace3\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @Ace3\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "FreeInstanceSharer"
(*temporary) = "zhCN"
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by gaveer** [comment]
4x Couldn't open FreeInstanceSharer\Libs\AceLocale-3.0-6\AceLocale-3.0.xml

**Comment by LiangYuxuan** [comment]
fixed in 9f8c11e, please try latest release :)
