### ISSUE TITLE
Cant logout

### ISSUE THREAD

**Issue by gaveer** [LiangYuxuan/FreeInstanceSharer#2]
3x [ADDON_ACTION_BLOCKED] AddOn 'FreeInstanceSharer' tried to call the protected function 'CancelLogout()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `CancelLogout'
FrameXML\StaticPopup.lua:1843: in function `OnAccept'
FrameXML\StaticPopup.lua:5053: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
[C]: in function `Click'
...aceFreeInstanceSharer\FreeInstanceSharer-v8.1.1.lua:316: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by gaveer** [comment]
zhCN is still showing 
-----------------------------------
1x FreeInstanceSharer\Locales\zhCN-Simplified Chinese.lua:4: attempt to index local 'L' (a nil value)
FreeInstanceSharer\Locales\zhCN-Simplified Chinese.lua:4: in main chunk

Locals:
addonName = "FreeInstanceSharer"
addon = <table> {
}
L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @Ace3\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @Ace3\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "FreeInstanceSharer"
(*temporary) = "zhCN"
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by LiangYuxuan** [comment]
Which version are you using? I can't reproduce the latter one on v8.1.1.

For the cannot logout issue, it works as intended to stop logging out when you afk for a while. You can uncheck the Prevent AFK toggle in config.

**Comment by gaveer** [comment]
its reproduce on German servers

**Comment by LiangYuxuan** [comment]
I think maybe AceLocale causes the issue, then I removed it and released a new version. Please try latest release :)
