### ISSUE TITLE
8.1.2 Error

### ISSUE THREAD

**Issue by gaveer** [LiangYuxuan/FreeInstanceSharer#3]
8x FreeInstanceSharer\Config.lua:236: attempt to concatenate field 'NAME - The name and realm of current character.' (a boolean value)
FreeInstanceSharer\Config.lua:236: in main chunk

Locals:
addonName = "FreeInstanceSharer"
addon = <table> {
 Core = <table> {
 }
 L = <table> {
 }
}
Core = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 PLAYER_CAMPING = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:313
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:172
 CHAT_MSG_BN_WHISPER = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:333
 CHAT_MSG_PARTY = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:385
 ScheduleRepeatingTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "FreeInstanceSharer"
 GROUP_ROSTER_UPDATE = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:355
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 inviteToGroup = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:256
 CHAT_MSG_WHISPER = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:320
 UPDATE_INSTANCE_INFO = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:288
 addToQueue = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:209
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:184
 removeFromQueue = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:242
 leaveGroup = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:274
 format = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:197
 RegisterBucketMessage = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:200
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 OnUpdate = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:151
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 OnEnable = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:125
 debug = <function> defined @FreeInstanceSharer\FreeInstanceSharer.lua:56
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 UnregisterAllBuckets = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:229
 enabledState = true
 addonPrefix = "|cFF70B8FFFreeInstanceSharer|r:"
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UnregisterBucket = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:206
 printStatus = <function>

**Comment by gaveer** [comment]
and the addone config is gon from the addone list on the interface

**Comment by gaveer** [comment]
i downgrade to 8.1.1 
deleted the Zh Locales
edit the FreeInstanceSharer.Lua
line 66 : 
local defaultConfig = {
    ["debug"] = false, -- Debug mode
    ["enable"] = false, -- Enable
    ["inviteOnly"] = false, -- Invite Only Mode
    ["preventAFK"] = **false**, -- Prevent AFK

 and its work without any issues

**Comment by LiangYuxuan** [comment]
Updated locale again, it should work this time.

I think unchecking Prevent AFK in config should allow logging out. Is it still failing?
It is a workaround as Blizzard don't allows addons to click cancel logout button, but if an error happens, the logout will be interrupted, then we can stop logging out due to long time afk. That's why you will see the error.

**Comment by gaveer** [comment]
going to test it later Tomorrow

**Comment by gaveer** [comment]
check this miss-placed 
http://prntscr.com/ndhing
